FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine3.19 as prepare
WORKDIR /app
RUN adduser -u 1000 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine3.19 as build
WORKDIR /src
COPY ["./WebApp.csproj", "./WebApp.csproj"]
RUN dotnet restore "./WebApp.csproj"
COPY . .
RUN dotnet publish "./WebApp.csproj" \
    -c Release \
    --no-restore \
    /p:PublishAot=false \
    -o "../app"

FROM prepare as final
COPY --chown=appuser --from=build /app .
ENTRYPOINT ["dotnet", "WebApp.dll"]
